# Generated by Django 4.0.2 on 2022-03-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=30)),
                ('Comics', models.CharField(max_length=20)),
            ],
        ),
    ]
